// ===========================================
//   БЕСКОНЕЧНОЕ ОРУЖИЕ (51 вид)
// ===========================================
const infiniteWeapons = [
    {
        id: 1,
        name: "Базука",
        image: "https://i.ibb.co/XrwwvSSx/Screenshot-20260902-195424-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "60 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Снаряды подвержены ветру, особенно на низких скоростях."
    },
    {
        id: 2,
        name: "Граната",
        image: "https://i.ibb.co/N209mRyG/Screenshot-20260902-195428-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "60 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Не подвержена ветру, проста в управлении."
    },
    {
        id: 3,
        name: "Отбойный молоток",
        image: "https://i.ibb.co/39LpCgmh/Screenshot-20260902-195438-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "5 ед. за удар",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Прорывает вертикальные тоннели. Для остановки нажмите стрельбу ещё раз."
    },
    {
        id: 4,
        name: "Динамит",
        image: "https://i.ibb.co/kV1nXDBT/Screenshot-20260902-195445-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "75 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Взрывается через 3 секунды, сильно толкает врага."
    },
    {
        id: 5,
        name: "Узи",
        image: "https://i.ibb.co/TMZCZMhh/Screenshot-20260902-195451-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "16 пуль по 5 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Короткие очереди, почти без разброса. Можно менять угол стрельбы."
    },
    {
    id: 6,
    name: "Сюрикены",
    image: "https://i.ibb.co/q62krJp/Screenshot-20260902-195456-Wormix.jpg",
    type: "Бесконечное",
    level: "-",
    damage: "4×17",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "4 сюрикена за ход. Двойной урон при первом попадании по цели."
},
    {
        id: 7,
        name: "Липучая граната",
        image: "https://i.ibb.co/931VkTCH/Screenshot-20260902-195501-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "40 ед. взрыв + 7 осколков по 20 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Прилипает к поверхности, осколки летят вверх."
    },
    {
        id: 8,
        name: "Дробовик",
        image: "https://i.ibb.co/wFhwTpSb/Screenshot-20260902-195506-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "7 дробинок по 13 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Мощное оружие ближнего боя, большой разброс."
    },
    {
    id: 9,
    name: "Ружьё",
    image: "https://i.ibb.co/Gfgkz9Ls/Screenshot-20260902-195511-Wormix.jpg",
    type: "Бесконечное",
    level: "-",
    damage: "2×30",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Между выстрелами можно перемещаться."
},
    {
        id: 10,
        name: "Пулемёт",
        image: "https://i.ibb.co/1fsC1DCP/Screenshot-20260902-195517-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "20 пуль по 6 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Большой разброс, эффективен на близких дистанциях."
    },
    {
        id: 11,
        name: "Самонаводящаяся ракета",
        image: "https://i.ibb.co/FkqT5tHw/Screenshot-20260902-195522-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "60 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Летит к цели по кратчайшей траектории. Укажите цель на карте."
    },
    {
        id: 12,
        name: "Портативный телепорт",
        image: "https://i.ibb.co/R4vdLyzN/Screenshot-20260902-195529-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Перемещает бойца в точку броска. Не тратит ход."
    },
    {
        id: 13,
        name: "Электрогарпун",
        image: "https://i.ibb.co/BVTXFtGQ/Screenshot-20260902-195533-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "30 ед. + 8 ед. × 4 раза в сек.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Цепляет и тащит врага к стрелку."
    },
    {
        id: 14,
        name: "Ледяная базука",
        image: "https://i.ibb.co/35d02GhV/Screenshot-20260902-195538-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Замораживает врагов на 2 хода. Подвержена ветру."
    },
    {
        id: 15,
        name: "Мина",
        image: "https://i.ibb.co/3m4TXLM3/Screenshot-20260902-195542-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Взрывается при входе врага в зону. Установка не тратит ход, если никого нет."
    },
    {
        id: 16,
        name: "Котобазука",
        image: "https://i.ibb.co/G3cQ87Ld/Screenshot-20260902-195548-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "2 отскока по 50 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Стреляет котом, который отскакивает в случайном направлении."
    },
    {
        id: 17,
        name: "Бур",
        image: "https://i.ibb.co/SW79dxK/Screenshot-20260902-195553-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "24 ед. в секунду",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Прорывает горизонтальные тоннели. Для остановки нажмите стрельбу."
    },
    {
        id: 18,
        name: "Осколочная граната",
        image: "https://i.ibb.co/pjC5701s/Screenshot-20260902-195610-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "40 ед. взрыв + 8 осколков по 15 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Не подвержена ветру, эффективна в замкнутых пространствах."
    },
    {
        id: 19,
        name: "Бумеранг",
        image: "https://i.ibb.co/Y7Kn5G4f/Screenshot-20260902-195615-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "70 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "После удара отскакивает, можно поймать и бросить ещё раз. Сильно зависит от ветра."
    },
    {
    id: 20,
    name: "AK-47",
    image: "https://i.ibb.co/N6XCSVbJ/Screenshot-20260902-195621-Wormix.jpg",
    type: "Бесконечное",
    level: "-",
    damage: "2×4×16",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Одна пуля может прошить двух врагов."
},
    {
    id: 21,
    name: "Коктейль Молотова",
    image: "https://i.ibb.co/MyTcXtMV/Screenshot-20260902-195654-Wormix.jpg",
    type: "Бесконечное",
    level: "-",
    damage: "40 ед. взрыв",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Взрывается от земли, покрывает её горючей смесью."
},
    {
        id: 22,
        name: "Паразит",
        image: "https://i.ibb.co/hFXF6DNL/Screenshot-20260902-195659-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "40 ед. при попадании + 40 ед. при срабатывании",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Прикрепляется к врагу, замедляет и взрывается через 10 секунд."
    },
    {
        id: 23,
        name: "Мортира",
        image: "https://i.ibb.co/mVtmXzcp/Screenshot-20260902-195702-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "35 ед. взрыв + 6 осколков по 25 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Не подвержена ветру. Начальная скорость фиксирована."
    },
    {
    id: 24,
    name: "Огнемёт",
    image: "https://i.ibb.co/1Jtj8FwT/Screenshot-20260902-195705-Wormix.jpg",
    type: "Бесконечное",
    level: "-",
    damage: "12×3",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Струя напалма, земля продолжает гореть."
},
    {
        id: 25,
        name: "Снайперская винтовка",
        image: "https://i.ibb.co/YFxYtm2H/Screenshot-20260902-195709-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "90 ед. (первая цель), далее снижается",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Пробивает несколько врагов. Урон по ближним целям снижается."
    },
    {
        id: 26,
        name: "Гравитационная пушка",
        image: "https://i.ibb.co/C3mDBz8T/Screenshot-20260902-195712-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "2 выстрела по 20 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Отталкивает врага. Можно стрелять под ноги для прыжка."
    },
    {
        id: 27,
        name: "Мина-паук",
        image: "https://i.ibb.co/CKSZYz8Y/Screenshot-20260902-195719-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "65 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Подползает к врагу, взрывается при его движении. Отравляет ядом."
    },
    {
        id: 28,
        name: "Свин",
        image: "https://i.ibb.co/Z1Mj7f89/Screenshot-20260902-195722-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "90 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Движется в указанном направлении, взрывается по кнопке."
    },
    {
        id: 29,
        name: "Блокиратор",
        image: "https://i.ibb.co/qFr2v5XX/Screenshot-20260902-195726-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "75 ед. уничтожившему",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Блокирует лечение врага. Действует 6 ходов."
    },
    {
        id: 30,
        name: "Охранник",
        image: "https://i.ibb.co/XZmjvstx/Screenshot-20260902-195729-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "10 разрядов по 3 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Обстреливает врагов при приближении. Установка не тратит ход."
    },
    {
        id: 31,
        name: "Балка",
        image: "https://i.ibb.co/mCLm7FCJ/Screenshot-20260902-195733-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Используется как мост или лестница. Установка не тратит ход."
    },
    {
        id: 32,
        name: "Кувалда",
        image: "https://i.ibb.co/xtvJpRRL/Screenshot-20260902-195736-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "от 60 до 280 ед. (35% текущего HP)",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Мощный удар, вгоняет врага в землю."
    },
    {
        id: 33,
        name: "Веревка",
        image: "https://i.ibb.co/TJRk6mx/Screenshot-20260902-195739-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Позволяет забираться на препятствия. Не тратит ход."
    },
    {
        id: 34,
        name: "Газовая граната",
        image: "https://i.ibb.co/6ktYxNy/Screenshot-20260902-195742-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "50 ед. за ход",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Облако газа, наносит урон ядом всем в зоне. Держится 6 ходов."
    },
    {
        id: 35,
        name: "Электрошокер",
        image: "https://i.ibb.co/v6RFz9k3/Screenshot-20260902-195744-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "40 ед. + урон от падения",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Подбрасывает врага. Эффективен против нескольких целей."
    },
    {
    id: 36,
    name: "Лазерный луч",
    image: "https://i.ibb.co/sJp0bCMM/Screenshot-20260902-195747-Wormix.jpg",
    type: "Бесконечное",
    level: "-",
    damage: "32×3",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Прожигает землю и врагов. Можно управлять во время стрельбы."
},
    {
        id: 37,
        name: "Суперкабан",
        image: "https://i.ibb.co/k6MYMzVr/Screenshot-20260902-195750-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "90 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Управляемый полёт. Взрывается при столкновении."
    },
    {
        id: 38,
        name: "Антифриз",
        image: "https://i.ibb.co/qY16JDWF/Screenshot-20260902-195756-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Размораживает и защищает от заморозки на 2 хода. Добавляет 50 HP. Тратит ход!"
    },
    {
        id: 39,
        name: "Телепорт",
        image: "https://i.ibb.co/4wjXQx1p/Screenshot-20260902-195800-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Перемещает в любую точку, наносит урон в точке прибытия. Тратит ход."
    },
    {
        id: 40,
        name: "Экстренный телепорт",
        image: "https://i.ibb.co/ksN9PHSQ/Screenshot-20260902-195804-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Мгновенно переносит в случайную точку. Не тратит ход."
    },
    {
        id: 41,
        name: "Летающая тарелка",
        image: "https://i.ibb.co/4wL1pfFd/Screenshot-20260902-195809-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "80 ед. при падении",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Может перетаскивать объекты. Упадёт на врага и взорвётся."
    },
    {
        id: 42,
        name: "Бита",
        image: "https://i.ibb.co/bM9KJfcQ/Screenshot-20260902-195813-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Выбивает врага в направлении удара."
    },
    {
        id: 43,
        name: "Лазерный барьер",
        image: "https://i.ibb.co/d0b9mB3g/Screenshot-20260902-195817-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "15 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Создаёт заградительные лучи. Установка не тратит ход."
    },
    {
        id: 44,
        name: "Заземлитель",
        image: "https://i.ibb.co/tTCGcD5b/Screenshot-20260902-195820-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Не даёт врагам долго летать. Установка не тратит ход."
    },
    {
        id: 45,
        name: "Бункеролом",
        image: "https://i.ibb.co/QF3tmbyM/Screenshot-20260902-195824-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Падающая торпеда, бурит землю и взрывается."
    },
    {
        id: 46,
        name: "Удар напалмом",
        image: "https://i.ibb.co/STsQdxn/Screenshot-20260902-195827-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "6 ракет по 20 ед. + 30 ед. огня/сек",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Поджигает землю. Можно выбрать сторону удара."
    },
    {
        id: 47,
        name: "Авиаудар",
        image: "https://i.ibb.co/v6SvBBcM/Screenshot-20260902-195830-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "5 ракет по 50 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Сбрасывает ракеты в указанную точку. Не зависят от ветра."
    },
    {
    id: 48,
    name: "Метеорит",
    image: "https://i.ibb.co/0R0xHVPp/Screenshot-20260902-195833-Wormix.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "65 ед. взрыв + 4 осколка по 35",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Падает под случайным углом, распадается на куски."
},
    {
    id: 49,
    name: "Котоудар",
    image: "https://i.ibb.co/C32gVybr/Screenshot-20260902-195837-Wormix.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "3×2×50",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Сбрасывает котов, которые отскакивают. Можно выбрать сторону."
},
    {
        id: 50,
        name: "Арбузобомба",
        image: "https://i.ibb.co/xSnCggyV/Screenshot-20260902-195841-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "80 ед. взрыв + 6 кусков по 50 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Мощная осколочная граната."
    },
    {
        id: 51,
        name: "Гравимина",
        image: "https://i.ibb.co/C3XLYLTM/Screenshot-20260902-195716-Wormix.jpg",
        type: "Бесконечное",
        level: "3 ход",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Подбрасывает врага вверх, не наносит урона. Установка не тратит ход."
    }
];

// ===========================================
//   ШТУЧНОЕ ОРУЖИЕ (12 видов)
// ===========================================
const consumableWeapons = [
    {
        id: 1,
        name: "Докторская сумка",
        image: "https://i.ibb.co/CpK7x5q7/Screenshot-20260902-182554-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "Восстанавливает 75 ед. здоровья",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Восстанавливает здоровье союзникам рядом. Не тратит ход. На себя не действует."
    },
    {
        id: 2,
        name: "Ледяной орб",
        image: "https://i.ibb.co/sJKJFrnC/Screenshot-20260902-182600-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "50 (прямое) / 30 (осколки)",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Замораживает врагов на 2 хода. Осколки наводятся на цели. Зависят от ветра."
    },
    {
        id: 3,
        name: "Душемёт",
        image: "https://i.ibb.co/qMVLZ6b7/Screenshot-20260902-182605-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "16 душ по 4–8 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Души выбирают цель случайно, могут пройти сквозь землю. Урон зависит от здоровья стрелка."
    },
    {
        id: 4,
        name: "Наковальня",
        image: "https://i.ibb.co/LdQF3193/Screenshot-20260902-182612-Wormix.jpg",
        type: "Штучное",
        level: "5 ход",
        damage: "70 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Падает в указанную точку, вгоняет жертву в землю. Остаётся на поле."
    },
    {
        id: 5,
        name: "Зловонный арбуз",
        image: "https://i.ibb.co/20K4gPLb/Screenshot-20260902-182617-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "90 (взрыв) + 6×65 (куски)",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Протухший арбуз. Отравляет врагов. Выдерживает только 1 отскок."
    },
    {
        id: 6,
        name: "Скверная тыква",
        image: "https://i.ibb.co/GfcbTp4g/Screenshot-20260902-182620-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "10 ед. × 6 ходов",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Заменяет шапку врага. -10 к атаке и защите на 6 ходов. Два раза за бой."
    },
    {
        id: 7,
        name: "Гвоздевая граната",
        image: "https://i.ibb.co/nMQ2fQ3x/Screenshot-20260902-182623-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "12 гвоздей × 16 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Зависает в воздухе на 1.5 сек, обстреливает гвоздями ближайших бойцов."
    },
    {
        id: 8,
        name: "Марш зомби",
        image: "https://i.ibb.co/V0dMSZbC/Screenshot-20260902-182626-Wormix.jpg",
        type: "Штучное",
        level: "6 ход",
        damage: "40 ед. (при падении)",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Призывает 3 зомби в вашу команду. Урон не зависит от параметров."
    },
    {
        id: 9,
        name: "Зелье алхимика",
        image: "https://i.ibb.co/x86m0yzV/Screenshot-20260902-183256-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Меняет местами атаку и защиту цели. Действует до конца следующего хода. Не тратит ход."
    },
    {
        id: 10,
        name: "Перевязка",
        image: "https://i.ibb.co/fzR8bT17/Screenshot-20260902-183302-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "Восстанавливает 50% урона за прошлый ход",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Один раз за бой на каждого бойца. Не тратит ход."
    },
    {
        id: 11,
        name: "Антитоксин",
        image: "https://i.ibb.co/wFc5p0zg/Screenshot-20260902-183305-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "15 ед. × 6 ходов",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Защищает от яда на время действия. Не тратит ход."
    },
    {
        id: 12,
        name: "Буран",
        image: "https://i.ibb.co/wh6kVq98/Screenshot-20260902-183326-Wormix.jpg",
        type: "Штучное",
        level: "2 ход",
        damage: "5 льдинок × 40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Раз в бой. Проходит сквозь стены. Замораживает врагов на 2 хода."
    }
];

// ===========================================
//   АПГРЕЙД ПУШЕК (50 видов)
// ===========================================
const upgradeWeapons = [
    {
        id: 1,
        name: "Базука",
        image: "https://i.ibb.co/mCrRfZxQ/O-Tl-Kb-Emr-WY.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "60 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Снаряды подвержены ветру, особенно на низких скоростях."
    },
    {
        id: 2,
        name: "Отбойный молоток",
        image: "https://i.ibb.co/xSwm4SMg/Ll0am4u-KZIQ.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "5 ед. за удар",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Прорывает вертикальные тоннели. Для остановки нажмите стрельбу ещё раз."
    },
    {
        id: 3,
        name: "Граната",
        image: "https://i.ibb.co/twpTRtPK/f-Iz-Gbd-LV8-CI.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "60 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Не подвержена ветру, проста в управлении."
    },
    {
        id: 4,
        name: "Динамит",
        image: "https://i.ibb.co/YBgv8WRQ/s-Chrt-H4rjxw.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "75 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Взрывается через 3 секунды, сильно толкает врага."
    },
    {
        id: 5,
        name: "Узи",
        image: "https://i.ibb.co/G39rt7kp/m-Po-SUgiie0-E.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "16 пуль по 5 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Короткие очереди, почти без разброса. Можно менять угол стрельбы."
    },
    {
        id: 6,
        name: "Сюрикены",
        image: "https://i.ibb.co/PvhCkRKT/S-xg8o-AQYLw.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "4×17",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "4 сюрикена за ход. Двойной урон при первом попадании по цели."
    },
    {
        id: 7,
        name: "Липучая граната",
        image: "https://i.ibb.co/HfwLLRCs/cshxx-O97-DI0.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "40 ед. взрыв + 7 осколков по 20 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Прилипает к поверхности, осколки летят вверх."
    },
    {
        id: 8,
        name: "Дробовик",
        image: "https://i.ibb.co/YFkHGVt3/M1-JIZE39-VUA.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "7 дробинок по 13 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Мощное оружие ближнего боя, большой разброс."
    },
    {
        id: 9,
        name: "Ружьё",
        image: "https://i.ibb.co/PsD9t7V9/X7-RYjr-WYyc8.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "2×30",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Между выстрелами можно перемещаться."
    },
    {
        id: 10,
        name: "Пулемёт",
        image: "https://i.ibb.co/4gJYpvnG/g-Q1sf6t-JB8.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "20 пуль по 6 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Большой разброс, эффективен на близких дистанциях."
    },
    {
        id: 11,
        name: "Самонаводящаяся ракета",
        image: "https://i.ibb.co/Q2MGnFX/WWJLWw-UWsb-U.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "60 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Летит к цели по кратчайшей траектории. Укажите цель на карте."
    },
    {
        id: 12,
        name: "Портативный телепорт",
        image: "https://i.ibb.co/sdzBSKrK/z-DE8-Cg-Q8jm-I.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Перемещает бойца в точку броска. Не тратит ход."
    },
    {
        id: 13,
        name: "Электрогарпун",
        image: "https://i.ibb.co/q3D4q0Sb/pwzf-Yn2u-Bn-Q.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "30 ед. + 8 ед. × 4 раза в сек.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Цепляет и тащит врага к стрелку."
    },
    {
        id: 14,
        name: "Ледяная базука",
        image: "https://i.ibb.co/5hRrHyxT/d-Gb3x-Xz-Y7vk.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Замораживает врагов на 2 хода. Подвержена ветру."
    },
    {
        id: 15,
        name: "Мина",
        image: "https://i.ibb.co/FqJvRjWg/LOVAg-MHLs4-U.jpg",
        type: "Апгрейд",
        level: "2 ход",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Взрывается при входе врага в зону. Установка не тратит ход, если никого нет."
    },
    {
        id: 16,
        name: "Котобазука",
        image: "https://i.ibb.co/YFNC5Zdq/Hha-Kpbo-Znn4.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "2 отскока по 50 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Стреляет котом, который отскакивает в случайном направлении."
    },
    {
        id: 17,
        name: "Бур",
        image: "https://i.ibb.co/0RFgvdXS/8-Bt-Dp-Eau-Qpk.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "24 ед. в секунду",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Прорывает горизонтальные тоннели. Для остановки нажмите стрельбу."
    },
    {
        id: 18,
        name: "Бумеранг",
        image: "https://i.ibb.co/4n9VhLdY/u6s-ZPic5-0.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "70 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "После удара отскакивает, можно поймать и бросить ещё раз. Сильно зависит от ветра."
    },
    {
        id: 19,
        name: "Осколочная граната",
        image: "https://i.ibb.co/W4Yt42hG/6-GBRUUupscc.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "40 ед. взрыв + 8 осколков по 15 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Не подвержена ветру, эффективна в замкнутых пространствах."
    },
    {
        id: 20,
        name: "Лазерный луч",
        image: "https://i.ibb.co/Fk1WJKBt/ev-DId-Upp-MO0.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "32×3",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Прожигает землю и врагов. Можно управлять во время стрельбы."
    },
    {
        id: 21,
        name: "АК-47",
        image: "https://i.ibb.co/XkWkqqBL/q-R-peyoz-E8-Q.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "2×4×16",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Одна пуля может прошить двух врагов."
    },
    {
        id: 22,
        name: "Коктейль Молотова",
        image: "https://i.ibb.co/LXpGwqvC/7dh-Er-VHt9-ZE.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "40 ед. взрыв",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Взрывается от земли, покрывает её горючей смесью."
    },
    {
        id: 23,
        name: "Паразит",
        image: "https://i.ibb.co/JwMVhx8M/Ei-Ozl-D3v-ECM.jpg",
        type: "Апгрейд",
        level: "2 ход",
        damage: "40 ед. при попадании + 40 ед. при срабатывании",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Прикрепляется к врагу, замедляет и взрывается через 10 секунд."
    },
    {
        id: 24,
        name: "Мортира",
        image: "https://i.ibb.co/FkpCgrSH/h-HL6-Ecyz-Hug.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "35 ед. взрыв + 6 осколков по 25 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Не подвержена ветру. Начальная скорость фиксирована."
    },
    {
        id: 25,
        name: "Огнемёт",
        image: "https://i.ibb.co/RTK4mMzm/VH8-Xg-USKFBw.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "12×3",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Струя напалма, земля продолжает гореть."
    },
    {
        id: 26,
        name: "Снайперская винтовка",
        image: "https://i.ibb.co/qMmH7cYw/7sw-Eb-Qotlik.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "90 ед. (первая цель), далее снижается",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Пробивает несколько врагов. Урон по ближним целям снижается."
    },
    {
        id: 27,
        name: "Гравитационная пушка",
        image: "https://i.ibb.co/8vC7Q3L/6-Kg-AXnic-NN8.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "2 выстрела по 20 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Отталкивает врага. Можно стрелять под ноги для прыжка."
    },
    {
        id: 28,
        name: "Гравимина",
        image: "https://i.ibb.co/cc4Qx2xV/BHLAOATl-N6s.jpg",
        type: "Апгрейд",
        level: "3 ход",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Подбрасывает врага вверх, не наносит урона. Установка не тратит ход."
    },
    {
        id: 29,
        name: "Мина-паук",
        image: "https://i.ibb.co/ccn65KR0/1-DXVEYJHXUI.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "65 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Подползает к врагу, взрывается при его движении. Отравляет ядом."
    },
    {
        id: 30,
        name: "Свин",
        image: "https://i.ibb.co/8DYWkkNB/Wtb7o4-NFgo.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "90 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Движется в указанном направлении, взрывается по кнопке."
    },
    {
        id: 31,
        name: "Блокиратор",
        image: "https://i.ibb.co/VY6PjG3k/0p0e-Iduygac.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "75 ед. уничтожившему",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Блокирует лечение врага. Действует 6 ходов."
    },
    {
        id: 32,
        name: "Охранник",
        image: "https://i.ibb.co/vCLdDcdW/Z7-Ra7k-VS0-KA.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "10 разрядов по 3 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Обстреливает врагов при приближении. Установка не тратит ход."
    },
    {
        id: 33,
        name: "Балка",
        image: "https://i.ibb.co/gMQSmDyx/0o-J4-KEYATs.jpg",
        type: "Апгрейд",
        level: "2 ход",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Используется как мост или лестница. Установка не тратит ход."
    },
    {
        id: 34,
        name: "Газовая граната",
        image: "https://i.ibb.co/yFhbyPXq/Zf-WE37-YDHx-E.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "50 ед. за ход",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Облако газа, наносит урон ядом всем в зоне. Держится 6 ходов."
    },
    {
        id: 35,
        name: "Веревка",
        image: "https://i.ibb.co/B5yMQr8n/3gj-AZGy-K-qc.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Позволяет забираться на препятствия. Не тратит ход."
    },
    {
        id: 36,
        name: "Электрошокер",
        image: "https://i.ibb.co/CsKL2qC0/5n-PTVtu6p-g.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "40 ед. + урон от падения",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Подбрасывает врага. Эффективен против нескольких целей."
    },
    {
        id: 37,
        name: "Суперкабан",
        image: "https://i.ibb.co/dsYPg0Qr/CTj-Hn-EOZs-Mk.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "90 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Управляемый полёт. Взрывается при столкновении."
    },
    {
        id: 38,
        name: "Антифриз",
        image: "https://i.ibb.co/b5N3FFfX/s3uvv-Xj3-CIY.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Размораживает и защищает от заморозки на 2 хода. Добавляет 50 HP. Тратит ход!"
    },
    {
        id: 39,
        name: "Телепорт",
        image: "https://i.ibb.co/d3xzSF5/9w9-Gnzn-Ay-L8.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Перемещает в любую точку, наносит урон в точке прибытия. Тратит ход."
    },
    {
        id: 40,
        name: "Экстренный телепорт",
        image: "https://i.ibb.co/5xXtY3pg/TUo-Is-Ib-IDWk.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Мгновенно переносит в случайную точку. Не тратит ход."
    },
    {
        id: 41,
        name: "Летающая тарелка",
        image: "https://i.ibb.co/TD3sXZyc/ud2-TFf-H2-Gz0.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "80 ед. при падении",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Может перетаскивать объекты. Упадёт на врага и взорвётся."
    },
    {
        id: 42,
        name: "Бита",
        image: "https://i.ibb.co/x8KkZyH6/Yf-OS6tyi-NGg.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Выбивает врага в направлении удара."
    },
    {
        id: 43,
        name: "Лазерный барьер",
        image: "https://i.ibb.co/rGZWgmxg/KGPe-YYIPPPY.jpg",
        type: "Апгрейд",
        level: "2 ход",
        damage: "15 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Создаёт заградительные лучи. Установка не тратит ход."
    },
    {
        id: 44,
        name: "Заземлитель",
        image: "https://i.ibb.co/6JPtmNVB/KIE-ET1l-HM.jpg",
        type: "Апгрейд",
        level: "2 ход",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Не даёт врагам долго летать. Установка не тратит ход."
    },
    {
        id: 45,
        name: "Бункеролом",
        image: "https://i.ibb.co/whLJv1wt/e44-VDj-MRPj8.jpg",
        type: "Апгрейд",
        level: "2 ход",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Падающая торпеда, бурит землю и взрывается."
    },
    {
        id: 46,
        name: "Авиаудар",
        image: "https://i.ibb.co/vxTF6pG5/TXq-HO98-VE3-M.jpg",
        type: "Апгрейд",
        level: "2 ход",
        damage: "5 ракет по 50 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Сбрасывает ракеты в указанную точку. Не зависят от ветра."
    },
    {
        id: 47,
        name: "Удар напалмом",
        image: "https://i.ibb.co/tTzM5Sf7/Rw-Zq-F5-Dk32w.jpg",
        type: "Апгрейд",
        level: "2 ход",
        damage: "6 ракет по 20 ед. + 30 ед. огня/сек",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Поджигает землю. Можно выбрать сторону удара."
    },
    {
        id: 48,
        name: "Метеорит",
        image: "https://i.ibb.co/XZwb8cfP/ONWNBD6-CRV8.jpg",
        type: "Апгрейд",
        level: "2 ход",
        damage: "65 ед. взрыв + 4 осколка по 35",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Падает под случайным углом, распадается на куски."
    },
    {
        id: 49,
        name: "Котоудар",
        image: "https://i.ibb.co/tw9JSsVX/Hbhx7dv3s-E.jpg",
        type: "Апгрейд",
        level: "2 ход",
        damage: "3×2×50",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Сбрасывает котов, которые отскакивают. Можно выбрать сторону."
    },
    {
        id: 50,
        name: "Арбузобомба",
        image: "https://i.ibb.co/pjNQ3Kxb/f-Vq1-ZGie8-EA.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "80 ед. взрыв + 6 кусков по 50 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Мощная осколочная граната."
    }
];

