// ===========================================
//   БЕСКОНЕЧНОЕ ОРУЖИЕ (51 вид)
// ===========================================
const infiniteWeapons = [
    {
        id: 1,
        name: "Базука",
        image: "https://i.ibb.co/XrwwvSSx/Screenshot-20260902-195424-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "60 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Снаряды подвержены ветру, особенно на низких скоростях."
    },
    {
        id: 2,
        name: "Граната",
        image: "https://i.ibb.co/N209mRyG/Screenshot-20260902-195428-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "60 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Не подвержена ветру, проста в управлении."
    },
    {
        id: 3,
        name: "Отбойный молоток",
        image: "https://i.ibb.co/39LpCgmh/Screenshot-20260902-195438-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "5 ед. за удар",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Прорывает вертикальные тоннели. Для остановки нажмите стрельбу ещё раз."
    },
    {
        id: 4,
        name: "Динамит",
        image: "https://i.ibb.co/kV1nXDBT/Screenshot-20260902-195445-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "75 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Взрывается через 3 секунды, сильно толкает врага."
    },
    {
        id: 5,
        name: "Узи",
        image: "https://i.ibb.co/TMZCZMhh/Screenshot-20260902-195451-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "16 пуль по 5 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Короткие очереди, почти без разброса. Можно менять угол стрельбы."
    },
    {
    id: 6,
    name: "Сюрикены",
    image: "https://i.ibb.co/q62krJp/Screenshot-20260902-195456-Wormix.jpg",
    type: "Бесконечное",
    level: "-",
    damage: "4×17",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "4 сюрикена за ход. Двойной урон при первом попадании по цели."
},
    {
        id: 7,
        name: "Липучая граната",
        image: "https://i.ibb.co/931VkTCH/Screenshot-20260902-195501-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "40 ед. взрыв + 7 осколков по 20 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Прилипает к поверхности, осколки летят вверх."
    },
    {
        id: 8,
        name: "Дробовик",
        image: "https://i.ibb.co/wFhwTpSb/Screenshot-20260902-195506-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "7 дробинок по 13 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Мощное оружие ближнего боя, большой разброс."
    },
    {
    id: 9,
    name: "Ружьё",
    image: "https://i.ibb.co/Gfgkz9Ls/Screenshot-20260902-195511-Wormix.jpg",
    type: "Бесконечное",
    level: "-",
    damage: "2×30",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Между выстрелами можно перемещаться."
},
    {
        id: 10,
        name: "Пулемёт",
        image: "https://i.ibb.co/1fsC1DCP/Screenshot-20260902-195517-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "20 пуль по 6 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Большой разброс, эффективен на близких дистанциях."
    },
    {
        id: 11,
        name: "Самонаводящаяся ракета",
        image: "https://i.ibb.co/FkqT5tHw/Screenshot-20260902-195522-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "60 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Летит к цели по кратчайшей траектории. Укажите цель на карте."
    },
    {
        id: 12,
        name: "Портативный телепорт",
        image: "https://i.ibb.co/R4vdLyzN/Screenshot-20260902-195529-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Перемещает бойца в точку броска. Не тратит ход."
    },
    {
        id: 13,
        name: "Электрогарпун",
        image: "https://i.ibb.co/BVTXFtGQ/Screenshot-20260902-195533-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "30 ед. + 8 ед. × 4 раза в сек.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Цепляет и тащит врага к стрелку."
    },
    {
        id: 14,
        name: "Ледяная базука",
        image: "https://i.ibb.co/35d02GhV/Screenshot-20260902-195538-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Замораживает врагов на 2 хода. Подвержена ветру."
    },
    {
        id: 15,
        name: "Мина",
        image: "https://i.ibb.co/3m4TXLM3/Screenshot-20260902-195542-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Взрывается при входе врага в зону. Установка не тратит ход, если никого нет."
    },
    {
        id: 16,
        name: "Котобазука",
        image: "https://i.ibb.co/G3cQ87Ld/Screenshot-20260902-195548-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "2 отскока по 50 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Стреляет котом, который отскакивает в случайном направлении."
    },
    {
        id: 17,
        name: "Бур",
        image: "https://i.ibb.co/SW79dxK/Screenshot-20260902-195553-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "24 ед. в секунду",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Прорывает горизонтальные тоннели. Для остановки нажмите стрельбу."
    },
    {
        id: 18,
        name: "Осколочная граната",
        image: "https://i.ibb.co/pjC5701s/Screenshot-20260902-195610-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "40 ед. взрыв + 8 осколков по 15 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Не подвержена ветру, эффективна в замкнутых пространствах."
    },
    {
        id: 19,
        name: "Бумеранг",
        image: "https://i.ibb.co/Y7Kn5G4f/Screenshot-20260902-195615-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "70 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "После удара отскакивает, можно поймать и бросить ещё раз. Сильно зависит от ветра."
    },
    {
    id: 20,
    name: "AK-47",
    image: "https://i.ibb.co/N6XCSVbJ/Screenshot-20260902-195621-Wormix.jpg",
    type: "Бесконечное",
    level: "-",
    damage: "2×4×16",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Одна пуля может прошить двух врагов."
},
    {
    id: 21,
    name: "Коктейль Молотова",
    image: "https://i.ibb.co/MyTcXtMV/Screenshot-20260902-195654-Wormix.jpg",
    type: "Бесконечное",
    level: "-",
    damage: "40 ед. взрыв",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Взрывается от земли, покрывает её горючей смесью."
},
    {
        id: 22,
        name: "Паразит",
        image: "https://i.ibb.co/hFXF6DNL/Screenshot-20260902-195659-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "40 ед. при попадании + 40 ед. при срабатывании",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Прикрепляется к врагу, замедляет и взрывается через 10 секунд."
    },
    {
        id: 23,
        name: "Мортира",
        image: "https://i.ibb.co/mVtmXzcp/Screenshot-20260902-195702-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "35 ед. взрыв + 6 осколков по 25 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Не подвержена ветру. Начальная скорость фиксирована."
    },
    {
    id: 24,
    name: "Огнемёт",
    image: "https://i.ibb.co/1Jtj8FwT/Screenshot-20260902-195705-Wormix.jpg",
    type: "Бесконечное",
    level: "-",
    damage: "12×3",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Струя напалма, земля продолжает гореть."
},
    {
        id: 25,
        name: "Снайперская винтовка",
        image: "https://i.ibb.co/YFxYtm2H/Screenshot-20260902-195709-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "90 ед. (первая цель), далее снижается",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Пробивает несколько врагов. Урон по ближним целям снижается."
    },
    {
        id: 26,
        name: "Гравитационная пушка",
        image: "https://i.ibb.co/C3mDBz8T/Screenshot-20260902-195712-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "2 выстрела по 20 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Отталкивает врага. Можно стрелять под ноги для прыжка."
    },
    {
        id: 27,
        name: "Мина-паук",
        image: "https://i.ibb.co/CKSZYz8Y/Screenshot-20260902-195719-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "65 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Подползает к врагу, взрывается при его движении. Отравляет ядом."
    },
    {
        id: 28,
        name: "Свин",
        image: "https://i.ibb.co/Z1Mj7f89/Screenshot-20260902-195722-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "90 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Движется в указанном направлении, взрывается по кнопке."
    },
    {
        id: 29,
        name: "Блокиратор",
        image: "https://i.ibb.co/qFr2v5XX/Screenshot-20260902-195726-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "75 ед. уничтожившему",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Блокирует лечение врага. Действует 6 ходов."
    },
    {
        id: 30,
        name: "Охранник",
        image: "https://i.ibb.co/XZmjvstx/Screenshot-20260902-195729-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "10 разрядов по 3 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Обстреливает врагов при приближении. Установка не тратит ход."
    },
    {
        id: 31,
        name: "Балка",
        image: "https://i.ibb.co/mCLm7FCJ/Screenshot-20260902-195733-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Используется как мост или лестница. Установка не тратит ход."
    },
    {
        id: 32,
        name: "Кувалда",
        image: "https://i.ibb.co/xtvJpRRL/Screenshot-20260902-195736-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "от 60 до 280 ед. (35% текущего HP)",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Мощный удар, вгоняет врага в землю."
    },
    {
        id: 33,
        name: "Веревка",
        image: "https://i.ibb.co/TJRk6mx/Screenshot-20260902-195739-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Позволяет забираться на препятствия. Не тратит ход."
    },
    {
        id: 34,
        name: "Газовая граната",
        image: "https://i.ibb.co/6ktYxNy/Screenshot-20260902-195742-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "50 ед. за ход",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Облако газа, наносит урон ядом всем в зоне. Держится 6 ходов."
    },
    {
        id: 35,
        name: "Электрошокер",
        image: "https://i.ibb.co/v6RFz9k3/Screenshot-20260902-195744-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "40 ед. + урон от падения",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Подбрасывает врага. Эффективен против нескольких целей."
    },
    {
    id: 36,
    name: "Лазерный луч",
    image: "https://i.ibb.co/sJp0bCMM/Screenshot-20260902-195747-Wormix.jpg",
    type: "Бесконечное",
    level: "-",
    damage: "32×3",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Прожигает землю и врагов. Можно управлять во время стрельбы."
},
    {
        id: 37,
        name: "Суперкабан",
        image: "https://i.ibb.co/k6MYMzVr/Screenshot-20260902-195750-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "90 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Управляемый полёт. Взрывается при столкновении."
    },
    {
        id: 38,
        name: "Антифриз",
        image: "https://i.ibb.co/qY16JDWF/Screenshot-20260902-195756-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Размораживает и защищает от заморозки на 2 хода. Добавляет 50 HP. Тратит ход!"
    },
    {
        id: 39,
        name: "Телепорт",
        image: "https://i.ibb.co/4wjXQx1p/Screenshot-20260902-195800-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Перемещает в любую точку, наносит урон в точке прибытия. Тратит ход."
    },
    {
        id: 40,
        name: "Экстренный телепорт",
        image: "https://i.ibb.co/ksN9PHSQ/Screenshot-20260902-195804-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Мгновенно переносит в случайную точку. Не тратит ход."
    },
    {
        id: 41,
        name: "Летающая тарелка",
        image: "https://i.ibb.co/4wL1pfFd/Screenshot-20260902-195809-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "80 ед. при падении",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Может перетаскивать объекты. Упадёт на врага и взорвётся."
    },
    {
        id: 42,
        name: "Бита",
        image: "https://i.ibb.co/bM9KJfcQ/Screenshot-20260902-195813-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Выбивает врага в направлении удара."
    },
    {
        id: 43,
        name: "Лазерный барьер",
        image: "https://i.ibb.co/d0b9mB3g/Screenshot-20260902-195817-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "15 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Создаёт заградительные лучи. Установка не тратит ход."
    },
    {
        id: 44,
        name: "Заземлитель",
        image: "https://i.ibb.co/tTCGcD5b/Screenshot-20260902-195820-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Не даёт врагам долго летать. Установка не тратит ход."
    },
    {
        id: 45,
        name: "Бункеролом",
        image: "https://i.ibb.co/QF3tmbyM/Screenshot-20260902-195824-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Падающая торпеда, бурит землю и взрывается."
    },
    {
        id: 46,
        name: "Удар напалмом",
        image: "https://i.ibb.co/STsQdxn/Screenshot-20260902-195827-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "6 ракет по 20 ед. + 30 ед. огня/сек",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Поджигает землю. Можно выбрать сторону удара."
    },
    {
        id: 47,
        name: "Авиаудар",
        image: "https://i.ibb.co/v6SvBBcM/Screenshot-20260902-195830-Wormix.jpg",
        type: "Бесконечное",
        level: "2 ход",
        damage: "5 ракет по 50 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Сбрасывает ракеты в указанную точку. Не зависят от ветра."
    },
    {
    id: 48,
    name: "Метеорит",
    image: "https://i.ibb.co/0R0xHVPp/Screenshot-20260902-195833-Wormix.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "65 ед. взрыв + 4 осколка по 35",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Падает под случайным углом, распадается на куски."
},
    {
    id: 49,
    name: "Котоудар",
    image: "https://i.ibb.co/C32gVybr/Screenshot-20260902-195837-Wormix.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "3×2×50",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "Сбрасывает котов, которые отскакивают. Можно выбрать сторону."
},
    {
        id: 50,
        name: "Арбузобомба",
        image: "https://i.ibb.co/xSnCggyV/Screenshot-20260902-195841-Wormix.jpg",
        type: "Бесконечное",
        level: "-",
        damage: "80 ед. взрыв + 6 кусков по 50 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Мощная осколочная граната."
    },
    {
        id: 51,
        name: "Гравимина",
        image: "https://i.ibb.co/C3XLYLTM/Screenshot-20260902-195716-Wormix.jpg",
        type: "Бесконечное",
        level: "3 ход",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Подбрасывает врага вверх, не наносит урона. Установка не тратит ход."
    }
];

// ===========================================
//   ШТУЧНОЕ ОРУЖИЕ (12 видов)
// ===========================================
const consumableWeapons = [
    {
        id: 1,
        name: "Докторская сумка",
        image: "https://i.ibb.co/CpK7x5q7/Screenshot-20260902-182554-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "Восстанавливает 75 ед. здоровья",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Восстанавливает здоровье союзникам рядом. Не тратит ход. На себя не действует."
    },
    {
        id: 2,
        name: "Ледяной орб",
        image: "https://i.ibb.co/sJKJFrnC/Screenshot-20260902-182600-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "50 (прямое) / 30 (осколки)",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Замораживает врагов на 2 хода. Осколки наводятся на цели. Зависят от ветра."
    },
    {
        id: 3,
        name: "Душемёт",
        image: "https://i.ibb.co/qMVLZ6b7/Screenshot-20260902-182605-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "16 душ по 4–8 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Души выбирают цель случайно, могут пройти сквозь землю. Урон зависит от здоровья стрелка."
    },
    {
        id: 4,
        name: "Наковальня",
        image: "https://i.ibb.co/LdQF3193/Screenshot-20260902-182612-Wormix.jpg",
        type: "Штучное",
        level: "5 ход",
        damage: "70 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Падает в указанную точку, вгоняет жертву в землю. Остаётся на поле."
    },
    {
        id: 5,
        name: "Зловонный арбуз",
        image: "https://i.ibb.co/20K4gPLb/Screenshot-20260902-182617-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "90 (взрыв) + 6×65 (куски)",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Протухший арбуз. Отравляет врагов. Выдерживает только 1 отскок."
    },
    {
        id: 6,
        name: "Скверная тыква",
        image: "https://i.ibb.co/GfcbTp4g/Screenshot-20260902-182620-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "10 ед. × 6 ходов",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Заменяет шапку врага. -10 к атаке и защите на 6 ходов. Два раза за бой."
    },
    {
        id: 7,
        name: "Гвоздевая граната",
        image: "https://i.ibb.co/nMQ2fQ3x/Screenshot-20260902-182623-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "12 гвоздей × 16 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Зависает в воздухе на 1.5 сек, обстреливает гвоздями ближайших бойцов."
    },
    {
        id: 8,
        name: "Марш зомби",
        image: "https://i.ibb.co/V0dMSZbC/Screenshot-20260902-182626-Wormix.jpg",
        type: "Штучное",
        level: "6 ход",
        damage: "40 ед. (при падении)",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Призывает 3 зомби в вашу команду. Урон не зависит от параметров."
    },
    {
        id: 9,
        name: "Зелье алхимика",
        image: "https://i.ibb.co/x86m0yzV/Screenshot-20260902-183256-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Меняет местами атаку и защиту цели. Действует до конца следующего хода. Не тратит ход."
    },
    {
        id: 10,
        name: "Перевязка",
        image: "https://i.ibb.co/fzR8bT17/Screenshot-20260902-183302-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "Восстанавливает 50% урона за прошлый ход",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Один раз за бой на каждого бойца. Не тратит ход."
    },
    {
        id: 11,
        name: "Антитоксин",
        image: "https://i.ibb.co/wFc5p0zg/Screenshot-20260902-183305-Wormix.jpg",
        type: "Штучное",
        level: "-",
        damage: "15 ед. × 6 ходов",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Защищает от яда на время действия. Не тратит ход."
    },
    {
        id: 12,
        name: "Буран",
        image: "https://i.ibb.co/wh6kVq98/Screenshot-20260902-183326-Wormix.jpg",
        type: "Штучное",
        level: "2 ход",
        damage: "5 льдинок × 40 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "Раз в бой. Проходит сквозь стены. Замораживает врагов на 2 хода."
    }
];

// ===========================================
//   АПГРЕЙД ПУШЕК (15 видов)
// ===========================================
const upgradeWeapons = [
    {
        id: 1,
        name: "Связка динамита",
        image: "https://i.ibb.co/MkVrWqJf/Screenshot-20260902-234806-Wormix.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "75 ед. взрыв + 2×65 ед. шашки",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "💥 Улучшенный динамит. При взрыве отлетают 2 шашки, которые взрываются при столкновении с землёй или бойцом."
    },
    {
    id: 2,
    name: "Ножи мастера",
    image: "https://i.ibb.co/C3yJf7Kb/Screenshot-20260902-234835-Wormix.jpg",
    type: "Апгрейд",
    level: "-",
    damage: "5×22",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "🗡️ Улучшенные сюрикены. 5 ножей за ход. Траектория подсвечивается."
},
    {
        id: 3,
        name: "Липучие мины",
        image: "https://i.ibb.co/Wp4YRk0Q/Screenshot-20260902-234847-Wormix.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "40 ед. взрыв + 8×25 ед. осколки",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "🧨 Улучшенная липучая граната. Осколки, не попавшие в цель, остаются на земле как мины на 5 ходов."
    },
    {
    id: 4,
    name: "Джекхаммер",
    image: "https://i.ibb.co/B2x4kBTv/Screenshot-20260902-234855-Wormix.jpg",
    type: "Апгрейд",
    level: "-",
    damage: "2×84",
    maxUpgrade: "-",
    price: "-",
    upgradeCost: "-",
    comment: "🔫 Улучшенный дробовик. Два выстрела за ход. Опустошительное оружие ближнего боя."
},
    {
        id: 5,
        name: "Управляемый телепорт",
        image: "https://i.ibb.co/tPzYnsM1/Screenshot-20260902-234905-Wormix.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "🌀 Улучшенный телепорт. Можно переместиться во время полёта с задержкой 1 сек. Не тратит ход."
    },
    {
        id: 6,
        name: "Энергетическая винтовка",
        image: "https://i.ibb.co/fVcmKFzh/Screenshot-20260902-234910-Wormix.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "45 ед. + 3×30 ед. разряды",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "⚡ Улучшенный электрогарпун. Разряды сильно подбрасывают врага. Урон не зависит от атаки и брони."
    },
    {
        id: 7,
        name: "Сенсорная граната",
        image: "https://i.ibb.co/Tq1ZHvCQ/Screenshot-20260902-234931-Wormix.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "45 ед. взрыв + 9×15 ед. осколки",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "💣 Улучшение осколочной гранаты. Взрывается автоматически рядом с врагом. Не подвержена ветру."
    },
    {
        id: 8,
        name: "Осколочный разрушитель",
        image: "https://i.ibb.co/TDhpgP40/Screenshot-20260902-234949-Wormix.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "50 ед. взрыв + 5×35 ед. осколки",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "💥 Улучшение мортиры. Большой радиус. Осколки летят в сторону врага. Траектория подсвечивается."
    },
    {
        id: 9,
        name: "Горящий свин",
        image: "https://i.ibb.co/4ZjVP5JG/Screenshot-20260902-235008-Wormix.jpg",
        type: "Апгрейд",
        level: "2 ход",
        damage: "45 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "🔥 Улучшение свина. Во время движения разбрасывает огонь. Взорвать можно в любой момент."
    },
    {
        id: 10,
        name: "Негатор",
        image: "https://i.ibb.co/Rp02PzKB/Screenshot-20260902-235014-Wormix.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "10 ед. каждый ход",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "🛡️ Улучшение блокиратора. Действует 8 ходов. Наносит урон врагам с HP > 10%."
    },
    {
        id: 11,
        name: "Эластичная балка",
        image: "https://i.ibb.co/KcXcbH9y/Screenshot-20260902-235021-Wormix.jpg",
        type: "Апгрейд",
        level: "2 ход",
        damage: "-",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "📐 Улучшение балки. Можно изменять размер кнопками вверх/вниз. Не тратит ход."
    },
    {
        id: 12,
        name: "Морозящий газ",
        image: "https://i.ibb.co/KzGCkD3y/Screenshot-20260902-235029-Wormix.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "50 ед. за ход",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "❄️ Улучшение газовой гранаты. Замедляет врагов на 1 ход. Облако держится 5 ходов."
    },
    {
        id: 13,
        name: "Похититель",
        image: "https://i.ibb.co/XkVp4wWW/Screenshot-20260902-235042-Wormix.jpg",
        type: "Апгрейд",
        level: "-",
        damage: "95 ед. при падении",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "🛸 Улучшенная тарелка. Может переносить союзников и объекты. Урон при падении на врага — 95 ед."
    },
    {
        id: 14,
        name: "Зимний страж",
        image: "https://i.ibb.co/zCDcVkS/Screenshot-20260902-235053-Wormix.jpg",
        type: "Апгрейд",
        level: "2 ход",
        damage: "40 ед. при срабатывании",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "🧊 Улучшение заземлителя. Гасит огонь, защищает от заморозки, замораживает врагов на 1 ход."
    },
    {
        id: 15,
        name: "Точечный удар",
        image: "https://i.ibb.co/1fxJPTR5/Screenshot-20260902-235100-Wormix.jpg",
        type: "Апгрейд",
        level: "4 ход",
        damage: "5 ракет по 50 ед.",
        maxUpgrade: "-",
        price: "-",
        upgradeCost: "-",
        comment: "🎯 Улучшенный авиаудар. Ракеты наводятся на цель. Можно выбрать сторону удара."
    }
];
