// ========================================
//   БЕСКОНЕЧНОЕ ОРУЖИЕ (пока пусто)
// ========================================
const infiniteWeapons = [
  {
    id: 1,
    name: "Базука",
    image: "https://iili.io/nHaGTgt.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "60 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Снаряды подвержены ветру, особенно на низких скоростях."
  },
  {
    id: 2,
    name: "Граната",
    image: "https://iili.io/nHaGI1I.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "60 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Не подвержена ветру, проста в управлении."
  },
  {
    id: 3,
    name: "Отбойный молоток",
    image: "https://iili.io/nHaGzqN.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "5 ед. за удар",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Прорывает вертикальные тоннели. Для остановки нажмите стрельбу ещё раз."
  },
  {
    id: 4,
    name: "Динамит",
    image: "https://iili.io/nHaGnXR.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "75 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Взрывается через 3 секунды, сильно толкает врага."
  },
  {
    id: 5,
    name: "Узи",
    image: "https://iili.io/nHaGCzv.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "16 пуль по 5 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Короткие очереди, почти без разброса. Можно менять угол стрельбы."
  },
  {
    id: 6,
    name: "Сюрикены",
    image: "https://iili.io/nHaGfea.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "17 ед. за бросок (первое попадание двойное)",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "4 сюрикена за ход. Двойной урон при первом попадании по цели."
  },
  {
    id: 7,
    name: "Липучая граната",
    image: "https://iili.io/nHaGFdF.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "40 ед. взрыв + 7 осколков по 20 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Прилипает к поверхности, осколки летят вверх."
  },
  {
    id: 8,
    name: "Дробовик",
    image: "https://iili.io/nHaGK5g.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "7 дробинок по 13 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Мощное оружие ближнего боя, большой разброс."
  },
  {
    id: 9,
    name: "Ружьё",
    image: "https://iili.io/nHaG2g1.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "30 ед. за выстрел, 2 выстрела",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Между выстрелами можно перемещаться."
  },
  {
    id: 10,
    name: "Пулемёт",
    image: "https://iili.io/nHaGJqB.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "20 пуль по 6 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Большой разброс, эффективен на близких дистанциях."
  },
  {
    id: 11,
    name: "Самонаводящаяся ракета",
    image: "https://iili.io/nHaEyWQ.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "60 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Летит к цели по кратчайшей траектории. Укажите цель на карте."
  },
  {
    id: 12,
    name: "Портативный телепорт",
    image: "https://iili.io/nHaEpzx.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "—",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Перемещает бойца в точку броска. Не тратит ход."
  },
  {
    id: 13,
    name: "Электрогарпун",
    image: "https://iili.io/nHaEDOb.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "30 ед. + 8 ед. × 4 раза в сек.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Цепляет и тащит врага к стрелку."
  },
  {
    id: 14,
    name: "Ледяная базука",
    image: "https://iili.io/nHaEt5u.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "40 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Замораживает врагов на 2 хода. Подвержена ветру."
  },
  {
    id: 15,
    name: "Мина",
    image: "https://iili.io/nHaELg9.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "40 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Взрывается при входе врага в зону. Установка не тратит ход, если никого нет."
  },
  {
    id: 16,
    name: "Котобазука",
    image: "https://iili.io/nHaEifS.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "2 отскока по 50 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Стреляет котом, который отскакивает в случайном направлении."
  },
  {
    id: 17,
    name: "Бур",
    image: "https://iili.io/nHaE6s2.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "24 ед. в секунду",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Прорывает горизонтальные тоннели. Для остановки нажмите стрельбу."
  },
  {
    id: 18,
    name: "Осколочная граната",
    image: "https://iili.io/nHaE4Wl.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "40 ед. взрыв + 8 осколков по 15 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Не подвержена ветру, эффективна в замкнутых пространствах."
  },
  {
    id: 19,
    name: "Бумеранг",
    image: "https://iili.io/nHaErx4.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "70 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "После удара отскакивает, можно поймать и бросить ещё раз. Сильно зависит от ветра."
  },
  {
    id: 20,
    name: "AK-47",
    image: "https://iili.io/nHaESOG.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "2 очереди по 4 выстрела, 16 ед. за пулю",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Одна пуля может прошить двух врагов."
  },
  {
    id: 21,
    name: "Коктейль Молотова",
    image: "https://iili.io/nHaE8Rs.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "40 ед. взрыв + 30 ед. огня/сек",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Взрывается от земли, покрывает её горючей смесью."
  },
  {
    id: 22,
    name: "Паразит",
    image: "https://iili.io/nHaEvJn.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "40 ед. при попадании + 40 ед. при срабатывании",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Прикрепляется к врагу, замедляет и взрывается через 10 секунд."
  },
  {
    id: 23,
    name: "Мортира",
    image: "https://iili.io/nHaEeUX.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "35 ед. взрыв + 6 осколков по 25 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Не подвержена ветру. Начальная скорость фиксирована."
  },
  {
    id: 24,
    name: "Огнемёт",
    image: "https://iili.io/nHaEOlt.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "12 капель по 3 ед. + 30 ед. огня/сек",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Струя напалма, земля продолжает гореть."
  },
  {
    id: 25,
    name: "Снайперская винтовка",
    image: "https://iili.io/nHaEjiN.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "90 ед. (первая цель), далее снижается",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Пробивает несколько врагов. Урон по ближним целям снижается."
  },
  {
    id: 26,
    name: "Гравитационная пушка",
    image: "https://iili.io/nHaEhVp.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "2 выстрела по 20 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Отталкивает врага. Можно стрелять под ноги для прыжка."
  },
  {
    id: 27,
    name: "Мина-паук",
    image: "https://iili.io/nHaEVDv.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "65 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Подползает к врагу, взрывается при его движении. Отравляет ядом."
  },
  {
    id: 28,
    name: "Свин",
    image: "https://iili.io/nHaEGRa.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "90 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Движется в указанном направлении, взрывается по кнопке."
  },
  {
    id: 29,
    name: "Блокиратор",
    image: "https://iili.io/nHaEEHg.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "75 ед. уничтожившему",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Блокирует лечение врага. Действует 6 ходов."
  },
  {
    id: 30,
    name: "Охранник",
    image: "https://iili.io/nHaE0UF.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "10 разрядов по 3 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Обстреливает врагов при приближении. Установка не тратит ход."
  },
  {
    id: 31,
    name: "Балка",
    image: "https://iili.io/nHaEcKP.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "—",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Используется как мост или лестница. Установка не тратит ход."
  },
  {
    id: 32,
    name: "Кувалда",
    image: "https://iili.io/nHaEYiB.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "от 60 до 280 ед. (35% текущего HP)",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Мощный удар, вгоняет врага в землю."
  },
  {
    id: 33,
    name: "Веревка",
    image: "https://iili.io/nHaE7VV.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "—",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Позволяет забираться на препятствия. Не тратит ход."
  },
  {
    id: 34,
    name: "Газовая граната",
    image: "https://iili.io/nHaE5oQ.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "50 ед. за ход",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Облако газа, наносит урон ядом всем в зоне. Держится 6 ходов."
  },
  {
    id: 35,
    name: "Электрошокер",
    image: "https://iili.io/nHaETAb.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "40 ед. + урон от падения",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Подбрасывает врага. Эффективен против нескольких целей."
  },
  {
    id: 36,
    name: "Лазерный луч",
    image: "https://iili.io/nHaEIHu.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "32 удара по 3 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Прожигает землю и врагов. Можно управлять во время стрельбы."
  },
  {
    id: 37,
    name: "Суперкабан",
    image: "https://iili.io/nHaExSe.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "90 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Управляемый полёт. Взрывается при столкновении."
  },
  {
    id: 38,
    name: "Антифриз",
    image: "https://iili.io/nHaEol9.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "—",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Размораживает и защищает от заморозки на 2 хода. Добавляет 50 HP. Тратит ход!"
  },
  {
    id: 39,
    name: "Телепорт",
    image: "https://iili.io/nHaEnK7.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "40 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Перемещает в любую точку, наносит урон в точке прибытия. Тратит ход."
  },
  {
    id: 40,
    name: "Экстренный телепорт",
    image: "https://iili.io/nHaEqV2.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "—",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Мгновенно переносит в случайную точку. Не тратит ход."
  },
  {
    id: 41,
    name: "Летающая тарелка",
    image: "https://iili.io/nHaEfol.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "80 ед. при падении",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Может перетаскивать объекты. Упадёт на врага и взорвётся."
  },
  {
    id: 42,
    name: "Бита",
    image: "https://iili.io/nHaE2AG.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "40 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Выбивает врага в направлении удара."
  },
  {
    id: 43,
    name: "Лазерный барьер",
    image: "https://iili.io/nHaEd9s.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "15 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Создаёт заградительные лучи. Установка не тратит ход."
  },
  {
    id: 44,
    name: "Заземлитель",
    image: "https://iili.io/nHaEFt4.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "40 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Не даёт врагам долго летать. Установка не тратит ход."
  },
  {
    id: 45,
    name: "Бункеролом",
    image: "https://iili.io/nHaEHSn.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "40 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Падающая торпеда, бурит землю и взрывается."
  },
  {
    id: 46,
    name: "Удар напалмом",
    image: "https://iili.io/nHa1yFt.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "6 ракет по 20 ед. + 30 ед. огня/сек",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Поджигает землю. Можно выбрать сторону удара."
  },
  {
    id: 47,
    name: "Авиаудар",
    image: "https://iili.io/nHa1bMN.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "5 ракет по 50 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Сбрасывает ракеты в указанную точку. Не зависят от ветра."
  },
  {
    id: 48,
    name: "Метеорит",
    image: "https://iili.io/nHa1mPI.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "65 ед. + 4 осколка по 35 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Падает под случайным углом, распадается на куски."
  },
  {
    id: 49,
    name: "Котоудар",
    image: "https://iili.io/nHa1Dnp.jpg",
    type: "Бесконечное",
    level: "2 ход",
    damage: "3 кота, 2 отскока по 50 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Сбрасывает котов, которые отскакивают. Можно выбрать сторону."
  },
  {
    id: 50,
    name: "Арбузобомба",
    image: "https://iili.io/nHa1ZtR.jpg",
    type: "Бесконечное",
    level: "—",
    damage: "80 ед. взрыв + 6 кусков по 50 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Мощная осколочная граната."
  },
  {
    id: 51,
    name: "Гравимина",
    image: "https://iili.io/nHaEXxR.jpg",
    type: "Бесконечное",
    level: "3 ход",
    damage: "—",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Подбрасывает врага вверх, не наносит урона. Установка не тратит ход."
  }
];

// ========================================
//   ШТУЧНОЕ ОРУЖИЕ (12 видов)
// ========================================
const consumableWeapons = [
  {
    id: 1,
    name: "Докторская сумка",
    image: "https://iili.io/nHRBe7j.jpg",
    type: "Штучное",
    level: "—",
    damage: "Восстанавливает 75 ед. здоровья",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Восстанавливает здоровье союзникам рядом. Не тратит ход. На себя не действует."
  },
  {
    id: 2,
    name: "Ледяной орб",
    image: "https://iili.io/nHRBkkx.jpg",
    type: "Штучное",
    level: "—",
    damage: "50 (прямое) / 30 (осколки)",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Замораживает врагов на 2 хода. Осколки наводятся на цели. Зависят от ветра."
  },
  {
    id: 3,
    name: "Душемёт",
    image: "https://iili.io/nHRBvmQ.jpg",
    type: "Штучное",
    level: "—",
    damage: "16 душ по 4–8 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Души выбирают цель случайно, могут пройти сквозь землю. Урон зависит от здоровья стрелка."
  },
  {
    id: 4,
    name: "Наковальня",
    image: "https://iili.io/nHRBOdb.jpg",
    type: "Штучное",
    level: "5 ход",
    damage: "70 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Падает в указанную точку, вгоняет жертву в землю. Остаётся на поле."
  },
  {
    id: 5,
    name: "Зловонный арбуз",
    image: "https://iili.io/nHRBSIV.jpg",
    type: "Штучное",
    level: "—",
    damage: "90 (взрыв) + 6×65 (куски)",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Протухший арбуз. Отравляет врагов. Выдерживает только 1 отскок."
  },
  {
    id: 6,
    name: "Скверная тыква",
    image: "https://iili.io/nHRBUhB.jpg",
    type: "Штучное",
    level: "—",
    damage: "10 ед. × 6 ходов",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Заменяет шапку врага. -10 к атаке и защите на 6 ходов. Два раза за бой."
  },
  {
    id: 7,
    name: "Гвоздевая граната",
    image: "https://iili.io/nHRBgLP.jpg",
    type: "Штучное",
    level: "—",
    damage: "12 гвоздей × 16 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Зависает в воздухе на 1.5 сек, обстреливает гвоздями ближайших бойцов."
  },
  {
    id: 8,
    name: "Марш зомби",
    image: "https://iili.io/nHRB4B1.jpg",
    type: "Штучное",
    level: "6 ход",
    damage: "40 ед. (при падении)",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Призывает 3 зомби в вашу команду. Урон не зависит от параметров."
  },
  {
    id: 9,
    name: "Зелье алхимика",
    image: "https://iili.io/nHRB6EF.jpg",
    type: "Штучное",
    level: "—",
    damage: "—",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Меняет местами атаку и защиту цели. Действует до конца следующего хода. Не тратит ход."
  },
  {
    id: 10,
    name: "Перевязка",
    image: "https://iili.io/nHRBs2a.jpg",
    type: "Штучное",
    level: "—",
    damage: "Восстанавливает 50% урона за прошлый ход",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Один раз за бой на каждого бойца. Не тратит ход."
  },
  {
    id: 11,
    name: "Антитоксин",
    image: "https://iili.io/nHRBPrg.jpg",
    type: "Штучное",
    level: "—",
    damage: "15 ед. × 6 ходов",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Защищает от яда на время действия. Не тратит ход."
  },
  {
    id: 12,
    name: "Буран",
    image: "https://iili.io/nHRBQkv.jpg",
    type: "Штучное",
    level: "2 ход",
    damage: "5 льдинок × 40 ед.",
    maxUpgrade: "—",
    price: "—",
    upgradeCost: "—",
    comment: "Раз в бой. Проходит сквозь стены. Замораживает врагов на 2 хода."
  }
];

// ========== ШАПКИ (пока пусто) ==========
const hats = [];

// ========== АРТЕФАКТЫ (пока пусто) ==========
const artifacts = [];
